#!/usr/bin/env node

const os = require('os');
const path = require('path');
const { createSuite, writePayload, editPayload } = require('../lib/harness');

const suite = createSuite('validators');
const { fixtureDirectory, sdlcProject, projectFixture, runHook, report, finish } = suite;

const cases = [];
const blocks = (hook, name, payload, options = {}) => cases.push({ hook, name, payload, options, expected: 2 });
const passes = (hook, name, payload, options = {}) => cases.push({ hook, name, payload, options, expected: 0 });
const replaceAllPayload = (filePath, oldString, newString) => {
  const payload = editPayload(filePath, oldString, newString);
  payload.tool_input.replace_all = true;
  return payload;
};

const PLAN_WEB =
  '# Plan — feat (web)\n\n' +
  '### Stage 1 — [data] `api.list` — Fetch the list\n\n' +
  '- **Approach:** rung 2 (reuse): extends existing `ListRepository` · standard: agrees\n' +
  '- **Test:** `ListRepository returns rows`\n' +
  '- **Status:** done 2026-10-01\n\n' +
  '### Stage 2 — [ui] `body.list` — Show list\n\n' +
  '- **Approach:** rung 2 (reuse): existing `Table` component · standard: agrees\n' +
  '- **Test:** `renders four states`\n' +
  '- **Status:** pending\n';
const PLAN_WITH_STAGE_DEBT =
  '# Plan\n\n### Stage 1 — [data] `a` — A\n\n' +
  '- **Approach:** rung 2 (reuse): X · standard: agrees\n- **Status:** pending\n\n' +
  '### Stage 2 — [ui] `b` — B\n\n- **Test:** renders\n- **Status:** pending\n';
const TRD_WITH_RUNG =
  '## 1. Design\n\n**Approach (ladder rung · world-wide standard):** rung 2 (reuse) — existing client · ' +
  'standard: agrees\n\n## 2. Data\n\nText.\n';
const TRD_WITH_PLACEHOLDER = '## 1\n\n**Approach:** <rung>\n\n## 2\n\nText.\n';
const GOOD_TABLE = '# T\n\n| A | B |\n|---|---|\n| 1 | 2 |\n| 3 | 4 |\n';

const app = sdlcProject('app');
const inApp = (relativePath) => path.join(app, relativePath);
const scratch = projectFixture('scratch', { 'notes/.keep': '' });
const stateOnly = projectFixture('state-only', { '.alpha-sdlc/next/x.json': '{}' });
const fakeHome = projectFixture('fake-home', { '.alpha-sdlc/next/x.json': '{}', '.claude/projects/x/memory/.keep': '' });
const plans = sdlcProject('plans', {
  'docs/development/feat/plan-web.md': PLAN_WEB,
  'docs/development/debt/plan-web.md': PLAN_WITH_STAGE_DEBT,
  'docs/development/f/TRD-web.md': TRD_WITH_RUNG,
  'docs/development/g/TRD.md': TRD_WITH_PLACEHOLDER,
});
const planWeb = path.join(plans, 'docs/development/feat/plan-web.md');
const planWithDebt = path.join(plans, 'docs/development/debt/plan-web.md');
const trdWithRung = path.join(plans, 'docs/development/f/TRD-web.md');
const trdWithPlaceholder = path.join(plans, 'docs/development/g/TRD.md');
const mono = sdlcProject('mono', {
  'docs/basics/.alpha-sdlc.json': '{"allowLicenseHeader": true}',
  'packages/api/package.json': '{}',
});
const monoPackage = path.join(mono, 'packages', 'api');
const godoc = sdlcProject('godoc', { 'docs/basics/.alpha-sdlc.json': '{"allowPublicApiDocstrings": true}' });
const sources = sdlcProject('sources', {
  'src/template.ts': 'const s = `\n  line\n`;\n',
  'src/existing.ts': 'export const a = 1;\nexport const b = 2;\n',
});
const tables = sdlcProject('tables', {
  'docs/edit.md': GOOD_TABLE,
  'docs/debt.md': '# T\n\n| A | B |\n|---|---|\n| 1 | 2 | 3 |\n\nprose\n\n| C | D |\n|---|---|\n| 9 | 8 |\n',
  'docs/fence.md': '# T\n\n```js\nconst x = 1;\n```\n\n| A | B |\n|---|---|\n| 1 | 2 |\n',
  'docs/curly.md': '# T\n\n| A | B |\n|---|---|\n| “quoted” | 2 |\n',
});

const STAMP = '_Generated by `do-project-setup` · commit `a1b2c3d` · approved 2026-09-01_';
const PROFILE_DESCRIPTION = '> The app\'s logical entities and who owns them.';
const CLEAN_PROFILE_DOC = `# Domain Model — app\n\n${STAMP}\n\n${PROFILE_DESCRIPTION}\n\n## Entities\n\n- **User** — signs in.\n`;
const HISTORY_LINES =
  '_**+ `run-terminal` backend Stage 1 · 2026-09-23** — the resume invariant changed._\n\n' +
  '_**+ `project-setup` Stages 4–5 · 2026-09-16** — the ingest owns the transition._\n';
const POLLUTED_PROFILE_DOC =
  `# Domain Model — app\n\n${HISTORY_LINES}\n${STAMP}\n\n${PROFILE_DESCRIPTION}\n\n## Entities\n\n- **User** — signs in.\n- **Run** — one setup run.\n`;
const profiles = sdlcProject('profiles', {
  'docs/basics/06-domain-model.md': POLLUTED_PROFILE_DOC,
  'docs/basics/07-database.md': `# Database — app\n\n${STAMP}\n\n## Tables\n\n- \`users\` — one row per account.\n`,
  'docs/basics/20-tech-debt-register.md': `# Tech Debt Register — app\n\n${STAMP}\n\n## Paid (history)\n\n- first paid row\n`,
  'docs/basics/08-data-cache.md': `# Data & Cache — app\n\n${STAMP}\n\n## Caches\n\n- ~~**Board cache**~~ — removed.\n- **Session** — kept in memory.\n`,
});
const inProfiles = (relativePath) => path.join(profiles, relativePath);

const COMMENTS = 'validate-comments.js';
const inSource = (name) => inApp(path.join('src', name));

blocks(COMMENTS, 'a plain line comment', writePayload(inSource('a.ts'), '// explain this\nconst x = 1;\n'));
blocks(COMMENTS, 'a block comment', writePayload(inSource('a.ts'), '/* explain this */\nconst x = 1;\n'));
blocks(COMMENTS, 'a doc comment', writePayload(inSource('a.ts'), '/** what it does */\nexport const x = 1;\n'));
blocks(COMMENTS, 'a hash comment in python', writePayload(inSource('a.py'), '# explain this\nx = 1\n'));
blocks(COMMENTS, 'a python docstring', writePayload(inSource('a.py'), 'def f():\n    """what it does"""\n    return 1\n'));
blocks(COMMENTS, 'a comment after real code', writePayload(inSource('a.ts'), 'const x = 1; // per item\n'));
blocks(
  COMMENTS,
  'a comment on a continuation line that opens with a division slash',
  writePayload(inSource('a.ts'), 'const r = a\n  / count; // per item\n'),
);

passes(COMMENTS, 'a url inside a double-quoted string', writePayload(inSource('a.ts'), 'const s = "https://x.com/a";\n'));
passes(COMMENTS, 'a regex literal containing slashes', writePayload(inSource('a.ts'), 'const re = /a\\/\\/b/;\n'));
passes(COMMENTS, 'a machine directive', writePayload(inSource('a.ts'), '// eslint-disable-next-line\nconst x = 1;\n'));
passes(COMMENTS, 'a shebang', writePayload(inSource('a.sh'), '#!/usr/bin/env bash\necho hi\n'));
passes(COMMENTS, 'a file with no comments at all', writePayload(inSource('a.ts'), 'const x = 1;\nexport default x;\n'));
passes(
  COMMENTS,
  'a bare url on a continuation line of a template literal',
  writePayload(inSource('a.ts'), 'const s = `\n  see https://x.com/a\n`;\n'),
);
passes(
  COMMENTS,
  'comment-shaped text on a continuation line of a template literal',
  writePayload(inSource('a.ts'), 'const s = `\n  // sample line for the docs\n`;\n'),
);
passes(
  COMMENTS,
  'hash-shaped data inside a shell heredoc',
  writePayload(inSource('a.sh'), 'cat <<EOF\n# server config data\nEOF\n'),
);
passes(
  COMMENTS,
  'a template literal spanning lines then real code after it',
  writePayload(inSource('a.ts'), 'const s = `\n  plain text\n`;\nconst y = 2;\n'),
);

passes(COMMENTS, 'VC1 python floor division', writePayload(inApp('tools/split.py'), 'def half(total):\n    return total // 2\n'));
passes(
  COMMENTS,
  'VC2 an unquoted url in a shell script',
  writePayload(inApp('scripts/fetch.sh'), '#!/bin/sh\ncurl -s https://example.com/api/v1 > out.json\n'),
);
passes(COMMENTS, 'VC3 a bash ${var//pattern/repl} expansion', writePayload(inApp('scripts/path.sh'), '#!/bin/bash\necho ${PATH//:/ }\n'));
passes(COMMENTS, 'VC4 a noqa directive', writePayload(inApp('tools/imp.py'), 'import os  # noqa: F401\n'));
blocks(
  COMMENTS,
  'VC5 an explanatory comment after code',
  writePayload(inApp('src/retry.ts'), 'export const retry = (n: number) => n + 1; // explain the retry\n'),
);
passes(
  COMMENTS,
  'VC6 a scratch analysis script under /tmp, outside any SDLC root',
  writePayload('/tmp/scratch/analyze.py', 'import json\n# load the aggregates\ndata = json.load(open("a.json"))\n'),
);
passes(
  COMMENTS,
  'VC6 a scratch script in a temp project without docs/basics or .alpha-sdlc',
  writePayload(path.join(scratch, 'analyze.py'), '# load the aggregates\nx = 1\n'),
);
const licenseHeader = '// Copyright 2026 Example Corp. SPDX-License-Identifier: MIT\nexport const a = 1;\n';
passes(
  COMMENTS,
  'VC7a a license header allowed by the Org allowlist, session at the repo root',
  { ...writePayload(path.join(monoPackage, 'src', 'a.ts'), licenseHeader), cwd: mono },
  { cwd: mono },
);
passes(
  COMMENTS,
  'VC7b the same license header, session in a monorepo package directory',
  { ...writePayload(path.join(monoPackage, 'src', 'a.ts'), licenseHeader), cwd: monoPackage },
  { cwd: monoPackage },
);
passes(COMMENTS, 'VC8 a go build directive', writePayload(inApp('src/b.go'), '//go:build linux\n\npackage b\n'));
passes(
  COMMENTS,
  'VC9 a Go doc comment on an exported func when public-API docs are allowed',
  writePayload(path.join(godoc, 'pkg/api.go'), 'package api\n\n// Fetch returns the account balance.\nfunc Fetch() int { return 1 }\n'),
);
passes(
  COMMENTS,
  'VC10 a TS doc comment when public-API docs are allowed',
  writePayload(path.join(godoc, 'pkg/api.ts'), '/** Fetch returns the balance. */\nexport function fetch() { return 1 }\n'),
);
blocks(
  COMMENTS,
  'a Go doc comment when the Org allowlist is off',
  writePayload(inApp('pkg/api.go'), 'package api\n\n// Fetch returns the account balance.\nfunc Fetch() int { return 1 }\n'),
);
blocks(
  COMMENTS,
  'a Go comment inside a function body even when public-API docs are allowed',
  writePayload(path.join(godoc, 'pkg/body.go'), 'package api\n\nfunc Fetch() int {\n\t// add one for the header row\n\treturn 1\n}\n'),
);
blocks(
  COMMENTS,
  'a Go comment above an unexported func even when public-API docs are allowed',
  writePayload(path.join(godoc, 'pkg/private.go'), 'package api\n\n// fetch returns the balance.\nfunc fetch() int { return 1 }\n'),
);
passes(
  COMMENTS,
  'Go doc comments on a grouped const and an exported struct field when public-API docs are allowed',
  writePayload(
    path.join(godoc, 'pkg/types.go'),
    'package api\n\nconst (\n\t// StatusReady marks a finished run.\n\tStatusReady = "ready"\n)\n\n' +
    '// Account holds a balance.\ntype Account struct {\n\t// Balance is in cents.\n\tBalance int\n}\n',
  ),
);
blocks(
  COMMENTS,
  'a narrative Go comment above a test function even when public-API docs are allowed',
  writePayload(
    path.join(godoc, 'pkg/api_test.go'),
    'package api\n\n// A user hit this path once, so the case stays.\nfunc TestFetch(t *testing.T) {}\n',
  ),
);
blocks(
  COMMENTS,
  'a Go comment above an exported func that does not start with its name',
  writePayload(path.join(godoc, 'pkg/narrative.go'), 'package api\n\n// This exists because the old path broke.\nfunc Fetch() int { return 1 }\n'),
);
passes(
  COMMENTS,
  'a KDoc holding a nested block comment when public-API docs are allowed',
  writePayload(
    path.join(godoc, 'src/UseCase.kt'),
    '/**\n * Usage:\n * useCase.observe().collect { events -> /* handle updates */ }\n * useCase.count().collect { /* handle count */ }\n */\n' +
    'class UseCase\n',
  ),
);
blocks(
  COMMENTS,
  'a KDoc holding a nested block comment is one finding when docs are not allowed',
  writePayload(
    inSource('UseCase.kt'),
    '/**\n * Usage:\n * useCase.observe().collect { events -> /* handle updates */ }\n * useCase.count().collect { /* handle count */ }\n */\n' +
    'class UseCase\n',
  ),
  { stderrIncludes: ['Comment in source code — 1 to delete'] },
);
passes(
  COMMENTS,
  'a multi-line Apache license header when license headers are allowed',
  writePayload(
    path.join(monoPackage, 'src', 'license.ts'),
    '// Copyright 2026 Example Corp.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n' +
    '// you may not use this file except in compliance with the License.\n//\n' +
    '// Unless required by applicable law or agreed to in writing, software\n' +
    '// distributed under the License is distributed on an "AS IS" BASIS.\nexport const a = 1;\n',
  ),
);
blocks(COMMENTS, 'a license header when the Org allowlist is off', writePayload(inSource('lic.ts'), licenseHeader));
blocks(
  COMMENTS,
  'every comment in the change is listed with its line',
  writePayload(inSource('three.ts'), '// first\nconst a = 1;\n// second\nconst b = 2;\n// third\n'),
  { stderrIncludes: ['line 1: // first', 'line 3: // second', 'line 5: // third', 'Comment in source code — 3'] },
);
passes(
  COMMENTS,
  'a hash line inside a python triple-quoted string',
  writePayload(inSource('help.py'), 'HELP = """\n# Usage\nrun it\n"""\n'),
);
passes(
  COMMENTS,
  'a triple-quoted SQL argument inside parentheses is not a docstring',
  writePayload(inSource('query.py'), 'rows = run(\n    """\n    SELECT 1\n    """\n)\n'),
);
blocks(COMMENTS, 'a python comment glued to code', writePayload(inSource('glued.py'), 'x = 1# note\n'));
passes(
  COMMENTS,
  'a hash line inside a multi-line double-quoted shell string',
  writePayload(inSource('inline.sh'), '#!/bin/sh\npython3 -c "\nimport sys\n# not a shell comment\nprint(1)\n"\n'),
);
blocks(COMMENTS, 'a trailing shell comment', writePayload(inSource('trail.sh'), 'echo hi # say hi\n'));
blocks(COMMENTS, 'a SQL dash comment', writePayload(inSource('q.sql'), 'SELECT 1; -- explain\n'));
blocks(COMMENTS, 'a SQL block comment', writePayload(inSource('q.sql'), 'SELECT a FROM t; /* why */\n'));
passes(COMMENTS, 'slashes inside a SQL string', writePayload(inSource('q.sql'), "SELECT 'http://x' AS url;\n"));
passes(
  COMMENTS,
  'a url inside a Kotlin raw string',
  writePayload(inSource('Url.kt'), 'val url = """\n    https://example.com/a\n"""\n'),
);
passes(
  COMMENTS,
  'a heading line inside a Ruby heredoc',
  writePayload(inSource('text.rb'), 'TEXT = <<~MD\n  # Heading\n  body\nMD\n'),
);
passes(
  COMMENTS,
  'an Edit that adds comment-shaped text inside a template literal already on disk',
  editPayload(path.join(sources, 'src/template.ts'), '  line\n', '  line\n  // sample\n'),
);
blocks(
  COMMENTS,
  'an Edit that adds a comment is reported at its line in the file',
  editPayload(path.join(sources, 'src/existing.ts'), 'export const b = 2;', '// b is the second\nexport const b = 2;'),
  { stderrIncludes: ['line 2: // b is the second'] },
);
passes(COMMENTS, 'a vendored dependency', writePayload(inApp('node_modules/x/index.js'), '// vendored\n'));
passes(COMMENTS, 'a generated file', writePayload(inSource('api.ts'), '// Code generated by openapi. DO NOT EDIT.\nexport {};\n'));
passes(
  COMMENTS,
  'an openapi-typescript schema marked auto-generated',
  writePayload(inSource('schema.d.ts'), '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\nexport {};\n'),
);
blocks(
  COMMENTS,
  'a project marked only by its .alpha-sdlc state directory',
  writePayload(path.join(stateOnly, 'src', 'a.ts'), '// explain this\nconst x = 1;\n'),
);

const RUNG = 'validate-rung.js';

blocks(
  RUNG,
  'a TRD whose Approach field is still a placeholder',
  writePayload(inApp('docs/development/f/TRD-web.md'), '## 1\n\n**Approach (ladder rung):** <rung>\n'),
);
blocks(
  RUNG,
  'a plan stage with no Approach field',
  writePayload(inApp('docs/development/f/plan-web.md'), '### Stage 1 — [domain] do the thing\n\n- **Goal:** x\n'),
);
passes(
  RUNG,
  'a TRD whose Approach names a rung',
  writePayload(inApp('docs/development/f/TRD-web.md'), '## 1\n\n**Approach (ladder rung):** rung 2 (reuse) — existing client\n'),
);
passes(RUNG, 'a plugin template is exempt', writePayload(inApp('skills/do-grooming/TRD-spoke-template.md'), '**Approach:** <rung>\n'));
passes(RUNG, 'an unrelated markdown file', writePayload(inApp('notes.md'), '**Approach:** <rung>\n'));

passes(
  RUNG,
  'VR1 a heading-only Edit of a stage whose Approach line is untouched',
  editPayload(planWeb, '### Stage 2 — [ui] `body.list` — Show list', '### Stage 2 — [ui] `body.list` — Show the transaction list'),
);
passes(
  RUNG,
  'VR2 an Edit that appends a Moved-in line to Stage 1, anchored on the next stage heading',
  editPayload(
    planWeb,
    '- **Status:** done 2026-10-01\n\n### Stage 2 — [ui] `body.list` — Show list',
    '- **Status:** done 2026-10-01\n- **Moved in:** AC-3 from Stage 2\n\n### Stage 2 — [ui] `body.list` — Show list',
  ),
);
passes(RUNG, 'VR3 a Status-line Edit', editPayload(planWeb, '- **Status:** pending', '- **Status:** done 2026-10-08'));
blocks(
  RUNG,
  'VR4 a plan Write with a stage lacking Approach',
  writePayload(
    path.join(plans, 'docs/development/feat/plan-android.md'),
    '# Plan\n\n### Stage 1 — [data] `a` — A\n\n- **Approach:** rung 2 (reuse): X · standard: agrees\n\n' +
    '### Stage 2 — [ui] `b` — B\n\n- **Test:** renders\n',
  ),
  { stderrIncludes: ['Stage 2 (line 7) has no **Approach** line'] },
);
passes(RUNG, 'VR5 a scratch plan-*.md under /tmp', writePayload('/tmp/notes/plan-ideas.md', '# Ideas\n\n### Stage 1 — try caching\n\nnotes only\n'));
passes(
  RUNG,
  'VR5 a plan-*.md in a temp project outside any SDLC root',
  writePayload(path.join(scratch, 'docs/development/x/plan-web.md'), '# Ideas\n\n### Stage 1 — try caching\n\nnotes only\n'),
);
passes(
  RUNG,
  'VR6 an Approach whose rung sits in an indented sub-bullet',
  writePayload(
    path.join(plans, 'docs/development/feat/plan-ios.md'),
    '# Plan\n\n### Stage 1 — [data] `a` — A\n\n- **Approach:**\n  - rung 2 (reuse): extends `ListRepository` · standard: agrees\n',
  ),
);
blocks(
  RUNG,
  'FN1 a bulleted Approach left empty',
  writePayload(path.join(plans, 'docs/development/fn/plan-web.md'), '# Plan\n\n### Stage 1 — [data] `a` — A\n\n- **Approach:**\n- **Test:** renders\n'),
);
blocks(
  RUNG,
  'FN2 a bulleted Approach left as <…>',
  writePayload(path.join(plans, 'docs/development/fn/plan-web.md'), '# Plan\n\n### Stage 1 — [data] `a` — A\n\n- **Approach:** <…>\n- **Test:** renders\n'),
);
blocks(
  RUNG,
  'FN3 an Edit that deletes a stage Approach line',
  editPayload(planWeb, '- **Approach:** rung 2 (reuse): existing `Table` component · standard: agrees\n', ''),
  { stderrIncludes: ['Stage 2'] },
);
blocks(
  RUNG,
  'FN4 an Edit that replaces a stage Approach line with another field',
  editPayload(planWeb, '- **Approach:** rung 2 (reuse): existing `Table` component · standard: agrees', '- **Notes:** none'),
);
blocks(
  RUNG,
  'the plan template placeholder wrapped onto a second line',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage 1 — [data] `a` — A\n\n' +
    '- **Approach:** <what / ladder rung · world-wide standard (agrees, or the surfaced conflict) — reuse\n' +
    '  X, native Y, etc.>\n- **Test:** renders\n',
  ),
);
passes(
  RUNG,
  'a rung named before the colon with its detail in a list below',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage 1 — [data] `a` — A\n\n**Approach** — rung 2 (reuse):\n- extends `ListRepository`\n- standard: agrees\n',
  ),
);
passes(
  RUNG,
  'an Approach whose rung follows a dash instead of a colon',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage 1 — [ui] `a` — A\n\n**Approach — rung 2 (reuse), with the signature doing the enforcing.** ' +
    '`heldAndCarryOn(questions)` holds it\n',
  ),
);
passes(
  RUNG,
  'a TRD Approach paragraph whose rungs follow as a table after a blank line',
  writePayload(
    inApp('docs/development/f/TRD.md'),
    '## 3. Design\n\n**Approach (ladder rung · world-wide standard):**\n\n| Slice | Rung |\n|---|---|\n| 0 | **Rung 1** — platform mechanism |\n',
  ),
);
passes(
  RUNG,
  'a TRD Approach paragraph whose rungs follow as a list after a blank line',
  writePayload(
    inApp('docs/development/f/TRD.md'),
    '## 3. Design\n\n**Approach (ladder rung · world-wide standard), by module:**\n\n- **Roles** — rung 2 (reuse) of the role helpers\n',
  ),
);
blocks(
  RUNG,
  'a TRD Approach paragraph followed only by the next heading',
  writePayload(inApp('docs/development/f/TRD.md'), '## 3. Design\n\n**Approach (ladder rung · world-wide standard):**\n\n## 4. Data\n'),
);
blocks(
  RUNG,
  'a letter-prefixed stage id without Approach',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage T2w-3 — [UI · section] overview\n\n- **Test:** renders\n',
  ),
  { stderrIncludes: ['Stage T2w-3 (line 3)'] },
);
passes(
  RUNG,
  'a "Stage breakdown" heading is not a stage',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage breakdown — approved 2026-10-08\n\n| Stage | Goal |\n|---|---|\n| 1 | a |\n',
  ),
);
passes(
  RUNG,
  'an Approach named mid-paragraph in a stage',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage 1 — [ui] `a` — A\n\nThe section stages already built its twelve crops. ' +
    '**Approach (ladder rung)**: **rung 1 — skip / YAGNI**: nothing is rebuilt.\n',
  ),
);
blocks(
  RUNG,
  'a dash-form Approach with nothing after the dash',
  writePayload(path.join(plans, 'docs/development/fn/plan-web.md'), '# Plan\n\n### Stage 1 — [ui] `a` — A\n\n**Approach —**\n'),
);
passes(
  RUNG,
  'a "Stage → slice map" heading is not a stage',
  writePayload(
    path.join(plans, 'docs/development/fn/plan-web.md'),
    '# Plan\n\n### Stage 1 — [data] `a` — A\n\n- **Approach:** rung 2 (reuse): X · standard: agrees\n\n' +
    '## Sequencing\n\n### Stage → slice map\n\n| Stage | Slice |\n|---|---|\n| 1 | a |\n',
  ),
);
passes(
  RUNG,
  'an Edit to one stage while another stage already lacks Approach',
  editPayload(
    planWithDebt,
    '- **Approach:** rung 2 (reuse): X · standard: agrees\n- **Status:** pending',
    '- **Approach:** rung 2 (reuse): X · standard: agrees\n- **Status:** done 2026-10-08',
  ),
);
blocks(
  RUNG,
  'an Edit to the stage that lacks Approach',
  editPayload(planWithDebt, '### Stage 2 — [ui] `b` — B', '### Stage 2 — [ui] `b` — Show B'),
);
passes(
  RUNG,
  'a replace_all Edit across both stages',
  replaceAllPayload(planWeb, 'standard: agrees', 'standard: agrees (checked)'),
);
passes(RUNG, 'an Edit whose old_string is not in the file', editPayload(planWeb, 'no such text', 'x'));
blocks(
  RUNG,
  'an Edit that writes a leftover date placeholder',
  editPayload(planWeb, '- **Status:** pending', '- **Status:** done <YYYY-MM-DD>'),
);
blocks(
  RUNG,
  'a TRD Edit that empties the Approach value',
  editPayload(trdWithRung, 'rung 2 (reuse) — existing client · standard: agrees', ''),
);
passes(
  RUNG,
  'a TRD Edit away from an Approach placeholder already on disk',
  editPayload(trdWithPlaceholder, 'Text.', 'More text.'),
);
blocks(
  RUNG,
  'a TRD Edit that touches the Approach placeholder',
  editPayload(trdWithPlaceholder, '**Approach:** <rung>', '**Approach:**  <rung>'),
);
passes(
  RUNG,
  'an Approach placeholder inside a fenced example',
  writePayload(inApp('docs/development/f/TRD-web.md'), '## 1\n\n**Approach:** rung 2 (reuse)\n\n```md\n**Approach:** <rung>\n```\n'),
);

const SECRETS = 'validate-no-secrets.js';

blocks(
  SECRETS,
  'an aws key in a profile doc',
  writePayload('/repo/docs/basics/09-environment.md', 'key: AKIAIOSFODNN7EXAMPLE\n'),
);
passes(
  SECRETS,
  'a named env var with no value',
  writePayload('/repo/docs/basics/09-environment.md', '| `AWS_ACCESS_KEY_ID` | from the vault |\n'),
);
passes(SECRETS, 'a source file is out of scope', writePayload('/repo/src/a.ts', 'const k = "AKIAIOSFODNN7EXAMPLE";\n'));

const TABLES = 'validate-doc-tables.js';
const appDoc = inApp('docs/x.md');

blocks(TABLES, 'a body row with more cells than its header', writePayload(appDoc, '# T\n\n| A | B |\n|---|---|\n| 1 | 2 | 3 |\n'));
blocks(TABLES, 'a body row with fewer cells than its header', writePayload(appDoc, '# T\n\n| A | B | C |\n|---|---|---|\n| 1 | 2 |\n'));
blocks(
  TABLES,
  'a header whose cell count differs from its delimiter row',
  writePayload(appDoc, '# T\n\n| A | B | C |\n|---|---|\n| 1 | 2 | 3 |\n'),
);
blocks(
  TABLES,
  'a row orphaned from its table by prose',
  writePayload(appDoc, '# T\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\nprose\n\n| 3 | 4 |\n'),
);
blocks(
  TABLES,
  'a row omitting its trailing pipe while carrying a surplus cell',
  writePayload(appDoc, '# T\n\n| A | B |\n|---|---|\n| 1 | 2 | 3\n'),
);
blocks(TABLES, 'an unclosed code fence', writePayload(appDoc, '# T\n\n```js\nconst x = 1;\n'));
passes(TABLES, 'a correct table', writePayload(appDoc, GOOD_TABLE));
passes(TABLES, 'a pipe table inside a fenced code block', writePayload(appDoc, '# T\n\n```\n| A | B |\n| 1 |\n```\n'));
passes(TABLES, 'a table indented two spaces', writePayload(appDoc, '# T\n\n  | A | B |\n  |---|---|\n  | 1 | 2 |\n'));
passes(TABLES, 'an escaped pipe inside a cell', writePayload(appDoc, '# T\n\n| A | B |\n|---|---|\n| a \\| b | 2 |\n'));

const tableFixture = path.join(tables, 'docs/edit.md');
blocks(TABLES, 'an Edit whose new row breaks the on-disk header', editPayload(tableFixture, '| 3 | 4 |', '| 3 | 4 | 5 |'));
blocks(TABLES, 'an Edit that deletes the delimiter row', editPayload(tableFixture, '|---|---|\n', ''));
blocks(TABLES, 'an Edit that replaces the delimiter row with prose', editPayload(tableFixture, '|---|---|', 'TODO fill in'));
passes(
  TABLES,
  'a correct Edit landing in a file with a pre-existing break elsewhere',
  editPayload(path.join(tables, 'docs/debt.md'), '| 9 | 8 |', '| 9 | 7 |'),
);
blocks(
  TABLES,
  'an Edit that deletes a closing fence outside the edited region',
  editPayload(path.join(tables, 'docs/fence.md'), 'const x = 1;\n```\n', 'const x = 1;\n'),
);

passes(
  TABLES,
  'VT1 an unfenced ASCII tree in a scratch markdown file',
  writePayload(path.join(scratch, 'notes/tree.md'), '# Layout\n\n|-- src\n|   |-- index.js\n'),
);
passes(TABLES, 'VT1 an ASCII tree under /tmp', writePayload('/tmp/notes/tree.md', '# Layout\n\n|-- src\n|   |-- index.js\n'));
passes(
  TABLES,
  'VT2 a Claude memory file with a ragged row',
  writePayload(path.join(os.homedir(), '.claude', 'projects', 'x', 'memory', 'notes.md'), '| a | b |\n|---|---|\n| 1 | 2 | 3 |\n'),
);
passes(
  TABLES,
  'a bare .alpha-sdlc/ in the home directory does not put all of home in scope',
  writePayload(path.join(fakeHome, '.claude', 'projects', 'x', 'memory', 'notes.md'), '| a | b |\n|---|---|\n| 1 | 2 | 3 |\n'),
  { env: { HOME: fakeHome } },
);
blocks(
  TABLES,
  'the same .alpha-sdlc/ outside the home directory still marks an SDLC root',
  writePayload(path.join(fakeHome, 'docs', 'notes.md'), '| a | b |\n|---|---|\n| 1 | 2 | 3 |\n'),
);
passes(
  TABLES,
  'VT3 a well-formed TRD table',
  writePayload(path.join(plans, 'docs/development/feat/TRD.md'), '| AC | Rule |\n|---|---|\n| AC-1 | loads |\n'),
);
blocks(
  TABLES,
  'VT4 an unescaped pipe inside a code span splits the cell',
  writePayload(path.join(plans, 'docs/development/feat/TRD.md'), '| AC | Rule |\n|---|---|\n| AC-1 | `a | b` filter |\n'),
);
blocks(
  TABLES,
  'an Edit whose straight quotes match curly quotes on disk is still checked',
  editPayload(path.join(tables, 'docs/curly.md'), '| "quoted" | 2 |', '| "quoted" | 2 | 3 |'),
);
blocks(
  TABLES,
  'an Edit that creates a new doc with a broken table',
  editPayload(path.join(tables, 'docs/new.md'), '', '# N\n\n| A | B |\n|---|---|\n| 1 |\n'),
);
blocks(
  TABLES,
  'a doc in a project marked only by its .alpha-sdlc state directory',
  writePayload(path.join(stateOnly, 'docs/notes.md'), '| A | B |\n|---|---|\n| 1 | 2 | 3 |\n'),
);

const BASH_DOCS = 'validate-bash-doc-writes.js';
const bashPayload = (command, cwd) => ({ tool_name: 'Bash', cwd: cwd || app, tool_input: { command } });

blocks(BASH_DOCS, 'a heredoc redirect into a TRD', bashPayload("cat > docs/development/x/TRD.md <<'EOF'\nhi\nEOF"));
blocks(BASH_DOCS, 'an append redirect into an absolute docs path', bashPayload(`echo x >> ${app}/docs/development/f/TRD.md`));
blocks(BASH_DOCS, 'sed -i on a profile doc', bashPayload("sed -i '' 's/a/b/' docs/basics/07-database.md"));
blocks(BASH_DOCS, 'perl -pi on a profile doc', bashPayload("perl -pi -e 's/a/b/' docs/basics/16-feature-map.md"));
blocks(BASH_DOCS, 'tee into a doc', bashPayload('printf x | tee docs/basics/a.md'));
blocks(
  BASH_DOCS,
  'a python heredoc that writes the hub',
  bashPayload("python3 - <<'PY'\nfrom pathlib import Path\nPath('docs/development/run-terminal/TRD.md').write_text('x')\nPY"),
);
blocks(BASH_DOCS, 'a copy from scratch onto a profile doc', bashPayload('cp "/tmp/scratch/02-architecture.md" docs/basics/02-architecture.md'));
blocks(
  BASH_DOCS,
  'a relative write after cd into a docs directory',
  bashPayload(`cd ${app}/docs/development/feature && cat >> TRD.md <<'EOF'\n## 2\nEOF`),
);
blocks(
  BASH_DOCS,
  'a relative write when the session cwd is inside docs',
  bashPayload('echo x >> TRD-web.md', inApp('docs/development/feature')),
);

passes(BASH_DOCS, 'reading a doc with cat', bashPayload('cat docs/development/x/TRD.md'));
passes(BASH_DOCS, 'grepping profile docs', bashPayload('grep -n foo docs/basics/*.md'));
passes(BASH_DOCS, 'copying a doc out to scratch', bashPayload('cp docs/basics/07-database.md /tmp/scratch/before.md'));
passes(BASH_DOCS, 'git checkout of a doc', bashPayload('git checkout -- docs/development/x/TRD.md'));
passes(BASH_DOCS, 'git add and commit of a doc', bashPayload('git add docs/development/x/TRD.md && git commit -m "docs: x"'));
passes(BASH_DOCS, 'a python read of a doc', bashPayload(`python3 -c "print(open('docs/a.md').read())"`));
passes(BASH_DOCS, 'a write outside docs', bashPayload('echo hi > /tmp/out.txt'));
passes(BASH_DOCS, 'a write to scratch that only reads docs', bashPayload('cat docs/basics/01-overview.md > /tmp/scratch/copy.md'));

passes(BASH_DOCS, 'VB1 a doc only read while tee writes to /tmp', bashPayload('grep -n "Stage" docs/development/feat/plan-web.md | tee /tmp/stages.txt'));
passes(
  BASH_DOCS,
  'VB2 a doc only read while Python writes a /tmp file',
  bashPayload(`wc -l docs/basics/02-architecture.md && python3 -c "open('/tmp/x.txt','w').write('1')"`),
);
passes(
  BASH_DOCS,
  'VB3 sed -i on a source file while a doc is only grepped',
  bashPayload("sed -i '' 's/foo/bar/' src/app.js && grep -c foo docs/basics/10-conventions.md"),
);
passes(BASH_DOCS, 'VB4 copying a doc out', bashPayload('cp docs/basics/02-architecture.md /tmp/arch.md'));
blocks(
  BASH_DOCS,
  'VB5 sed -i on a doc, and the block names the target and the batching remedy',
  bashPayload("sed -i '' 's/a/b/' docs/basics/02-architecture.md"),
  { stderrIncludes: ['sed -i: docs/basics/02-architecture.md', 'send all the Edit calls in one message'] },
);
passes(BASH_DOCS, 'VB6 a session cwd inside docs with a redirect to /tmp/notes.md', bashPayload('echo hi > /tmp/notes.md', inApp('docs')));
passes(
  BASH_DOCS,
  'VB7 a heredoc into a docs path of a temp project outside any SDLC root',
  bashPayload(`cat > ${scratch}/docs/development/feat/plan-web.md <<'EOF'\nx\nEOF`, scratch),
);
blocks(
  BASH_DOCS,
  'a for loop that runs sed -i over profile docs',
  bashPayload("for f in docs/basics/*.md; do sed -i '' 's/a/b/' \"$f\"; done"),
);
blocks(BASH_DOCS, 'xargs sed -i fed by a listing of docs', bashPayload("ls docs/basics/*.md | xargs sed -i '' 's/a/b/'"));
blocks(BASH_DOCS, 'find -exec sed -i over the docs tree', bashPayload("find docs -name '*.md' -exec sed -i '' 's/a/b/' {} +"));
blocks(BASH_DOCS, 'a doc write inside bash -c', bashPayload(`bash -c "sed -i '' 's/a/b/' docs/basics/01-overview.md"`));
blocks(BASH_DOCS, 'a doc write inside a command substitution', bashPayload(`echo "$(sed -i '' 's/a/b/' docs/basics/01-overview.md)"`));
blocks(BASH_DOCS, 'a relative write after cd inside a subshell', bashPayload("(cd docs/basics && sed -i '' 's/a/b/' 01-overview.md)"));
blocks(
  BASH_DOCS,
  'a python heredoc that names the doc on one line and writes it on another',
  bashPayload("python3 - <<'PY'\np = Path('docs/basics/01-overview.md')\ns = p.read_text()\np.write_text(s.replace('a', 'b'))\nPY"),
);
passes(
  BASH_DOCS,
  'a python heredoc that only reads a doc',
  bashPayload("python3 - <<'PY'\nprint(open('docs/basics/01-overview.md').read())\nPY"),
);
blocks(
  BASH_DOCS,
  'a python script written to scratch that writes a doc',
  bashPayload("cat > /tmp/fix.py <<'EOF'\nopen('docs/basics/01-overview.md', 'w').write('x')\nEOF\npython3 /tmp/fix.py"),
);
passes(
  BASH_DOCS,
  'a python script that reads a doc and writes its result to scratch',
  bashPayload("python3 - <<'PY'\nimport json\nrows = open('docs/basics/01-overview.md').read().split('\\n')\njson.dump(rows, open('/tmp/rows.json', 'w'))\nPY"),
);
passes(
  BASH_DOCS,
  'a python script inside docs whose markdown-looking text is a regex and whose write goes to scratch',
  bashPayload(
    "python3 - <<'PY'\nimport re, json\ns = open('page.html').read()\nrows = re.findall(r'>([a-z0-9-]+\\.md)<', s)\n" +
    "json.dump(rows, open('/tmp/ladder.json', 'w'))\nPY",
    inApp('docs/development/feat/design'),
  ),
);
blocks(
  BASH_DOCS,
  'a python script that writes scratch and then moves it onto a doc',
  bashPayload("python3 - <<'PY'\nimport shutil\nopen('/tmp/x.md', 'w').write('x')\nshutil.move('/tmp/x.md', 'docs/basics/01-overview.md')\nPY"),
);
blocks(
  BASH_DOCS,
  'a python script that builds the doc path with Path division',
  bashPayload("python3 - <<'PY'\nfrom pathlib import Path\nroot = '.'\n(Path(root) / 'docs' / 'basics' / '01-overview.md').write_text('x')\nPY"),
);
blocks(
  BASH_DOCS,
  'a python script that splits the docs path into concatenated strings',
  bashPayload(`python3 -c "\np='${app}/do'+'cs/basics/19-code-inventory.md'\nopen(p,'w').write('x')\n"`),
);
blocks(
  BASH_DOCS,
  'a python script that writes each path a loop hands it from the docs tree',
  bashPayload(`for f in docs/basics/*.md; do python3 - "$f" <<'EOF'\nimport sys\nopen(sys.argv[1], 'w').write('x')\nEOF\ndone`),
);
passes(
  BASH_DOCS,
  'a python script that writes each json path a loop hands it while a doc is committed',
  bashPayload(
    'git add docs/basics/01-overview.md && git commit -qm x; for f in .alpha-sdlc/auto-run.json sub/.alpha-sdlc/auto-run.json; ' +
    `do python3 -I - "$f" <<'EOF'\nimport json,sys\np=sys.argv[1]; d=json.load(open(p)); d['status']='halted'\njson.dump(d,open(p,'w'))\nEOF\ndone`,
  ),
);
blocks(
  BASH_DOCS,
  'a python loop over a list of doc names, run from inside docs',
  bashPayload(
    "python3 - <<'PY'\nfor p, old, new in [('gate.md', 'a', 'b'), ('question.md', 'c', 'd')]:\n    s = open(p).read()\n    open(p, 'w').write(s.replace(old, new))\nPY",
    inApp('docs/development/feat/section-slicing'),
  ),
);
passes(
  BASH_DOCS,
  'a node script that reads a doc and writes scratch',
  bashPayload(`node -e "const fs=require('fs');fs.writeFileSync('/tmp/out.json', JSON.stringify(fs.readFileSync('docs/basics/01-overview.md','utf8')))"`),
);
blocks(BASH_DOCS, 'a markdown file copied into a docs directory', bashPayload('cp /tmp/draft.md docs/basics/'));
passes(BASH_DOCS, 'a markdown write outside docs in the project', bashPayload('echo x > notes.md'));
passes(BASH_DOCS, 'grepping a doc for a write call', bashPayload('grep -n "\\.write(" docs/basics/01-overview.md'));
passes(BASH_DOCS, 'git show of a doc into scratch', bashPayload('git show HEAD:docs/basics/01-overview.md > /tmp/a.md'));
passes(BASH_DOCS, 'sed printing a doc', bashPayload("sed -n '1,5p' docs/basics/01-overview.md"));
blocks(
  BASH_DOCS,
  'sed -i on a doc named through $CLAUDE_PROJECT_DIR',
  bashPayload(`sed -i '' 's/a/b/' "$CLAUDE_PROJECT_DIR/docs/basics/01-overview.md"`, '/'),
  { env: { CLAUDE_PROJECT_DIR: app } },
);
blocks(
  BASH_DOCS,
  'a write into a child repo from a workspace-parent cwd',
  bashPayload(`sed -i '' 's/a/b/' ${path.basename(app)}/docs/basics/01-overview.md`, fixtureDirectory),
);

passes(TABLES, 'a profile doc whose head is its title, one stamp line and its description', writePayload(inProfiles('docs/basics/02-architecture.md'), CLEAN_PROFILE_DOC));
blocks(
  TABLES,
  'a profile doc whose head lists the updates it went through',
  writePayload(inProfiles('docs/basics/02-architecture.md'), POLLUTED_PROFILE_DOC),
  { stderrIncludes: ['Profile doc keeps history', '3 dates', 'ONE stamp line'] },
);
blocks(
  TABLES,
  'a re-stamp of a profile doc whose head still carries its update history',
  editPayload(inProfiles('docs/basics/06-domain-model.md'), STAMP, STAMP.replace('2026-09-01', '2026-10-09')),
  { stderrIncludes: ['Profile doc keeps history'] },
);
passes(
  TABLES,
  'an edit to a body section of a profile doc whose head carries history is not blocked',
  editPayload(inProfiles('docs/basics/06-domain-model.md'), '- **Run** — one setup run.', '- **Run** — one setup run, resumable.'),
);
blocks(
  TABLES,
  'a date closed by the italic underscore still counts',
  writePayload(
    inProfiles('docs/basics/19-code-inventory.md'),
    '# Code Inventory — app\n\n_Generated · commit `a2ffeb2` · approved 2026-09-19_ · _+ `git.CommitOf` registered · approved: auto 2026-10-08_\n\n## Rows\n',
  ),
  { stderrIncludes: ['2 dates'] },
);
blocks(
  TABLES,
  'a single dated head line that grew into a narrative',
  writePayload(
    inProfiles('docs/basics/05-tech-stack.md'),
    `# Tech Stack — app\n\n_Refreshed · commit \`e028559\` · 2026-08-13 — ${'the build block was re-read and found incomplete, '.repeat(4)}_\n\n## Stack\n`,
  ),
  { stderrIncludes: ['-character dated line'] },
);
blocks(
  TABLES,
  'a struck-through retired entity in an edited profile doc line',
  editPayload(inProfiles('docs/basics/07-database.md'), '- `users` — one row per account.', '- `users` — one row per account.\n- ~~`project_boards`~~ — retired.'),
  { stderrIncludes: ['strikes text through'] },
);
passes(
  TABLES,
  'struck text on the line next to an edit does not block that edit',
  editPayload(inProfiles('docs/basics/08-data-cache.md'), '- **Session** — kept in memory.', '- **Session** — kept in memory for an hour.'),
);
passes(
  TABLES,
  'the tech-debt register keeps its paid rows struck through',
  editPayload(inProfiles('docs/basics/20-tech-debt-register.md'), '- first paid row', '- ~~TD-1~~ first paid row — paid in `abc1234`'),
);
passes(
  TABLES,
  'a feature-map head ends at its table, so dated rows below it are body',
  writePayload(
    inProfiles('docs/basics/16-feature-map.md'),
    `# Feature Map — app\n\n${STAMP}\n\n| Feature | Status |\n|---|---|\n| board | built 2026-08-13 |\n| calendar | built 2026-09-30 |\n`,
  ),
);
passes(
  TABLES,
  'a TRD outside docs/basics is not a profile doc',
  writePayload(inProfiles('docs/development/feat/TRD.md'), `# TRD — feat\n\n${HISTORY_LINES}\n## 1. Overview\n`),
);

const drifted = sdlcProject('drifted', {
  'docs/development/feat/TRD.md': '# TRD\n',
  'docs/development/feat/.alpha-sdlc/handoff/last-stop/s1.md': 'summary\n',
  'docs/.alpha-sdlc/next/feat--web.json': '{}',
});
const driftedFeature = path.join(drifted, 'docs', 'development', 'feat');
blocks(BASH_DOCS, 'a state directory left inside a feature folder does not exempt its TRD', bashPayload('echo x >> TRD.md', driftedFeature));
blocks(BASH_DOCS, 'a state directory left inside docs/ does not exempt the docs below it',
  bashPayload('echo x >> docs/development/feat/TRD.md', drifted));
blocks(BASH_DOCS, 'a heredoc run by bash that edits a doc', bashPayload("bash <<'EOF'\nsed -i '' 's/a/b/' docs/basics/01-overview.md\nEOF"));
blocks(BASH_DOCS, 'a heredoc run by sh -s that appends to a doc', bashPayload("sh -s <<'EOF'\necho x >> docs/basics/01-overview.md\nEOF"));
blocks(BASH_DOCS, 'a heredoc run by zsh that overwrites a doc', bashPayload("zsh <<'EOF'\nprintf 'x' > docs/basics/01-overview.md\nEOF"));
blocks(BASH_DOCS, 'a heredoc run by bash -s that writes a TRD through its own heredoc',
  bashPayload("bash -s <<'EOF'\ncat > docs/development/feat/TRD.md <<'IN'\n# x\nIN\nEOF"));
blocks(BASH_DOCS, 'a here-string run by bash that edits a doc', bashPayload(`bash <<< "sed -i '' 's/a/b/' docs/basics/01-overview.md"`));
blocks(BASH_DOCS, 'a script piped into sh from a command that names the doc',
  bashPayload(`printf '%s\\n' "sed -i '' s/a/b/ docs/basics/01-overview.md" | sh`));
blocks(BASH_DOCS, 'sh -c under xargs on a {} fed from a docs listing', bashPayload("ls docs/basics/*.md | xargs -I{} sh -c 'sed -i \"\" s/a/b/ {}'"));
blocks(BASH_DOCS, 'sh -c under find -exec on the docs it finds', bashPayload("find docs -name '*.md' -exec sh -c 'sed -i \"\" s/a/b/ \"$1\"' _ {} \\;"));
passes(BASH_DOCS, 'a heredoc run by bash that writes scratch only', bashPayload("bash <<'EOF'\necho done > /tmp/alpha-sdlc-scratch.txt\nEOF"));
passes(BASH_DOCS, 'sh -c under xargs that only counts lines of the docs', bashPayload("ls docs/basics/*.md | xargs -I{} sh -c 'wc -l {}'"));
passes(BASH_DOCS, 'a doc piped into a named script is not a script piped into the shell', bashPayload('cat docs/basics/01-overview.md | bash scripts/count.sh'));
blocks(BASH_DOCS, 'a cd to the git top level, then sed -i on a doc', bashPayload(`cd "$(git rev-parse --show-toplevel)" && sed -i '' 's/a/b/' docs/basics/01-overview.md`));
blocks(BASH_DOCS, 'a cd through backticks, then a python write to a doc',
  bashPayload("cd `git rev-parse --show-toplevel` && python3 - <<'EOF'\nopen('docs/basics/01-overview.md','w').write('x')\nEOF"));
blocks(BASH_DOCS, 'cd - then an append to a doc', bashPayload('cd - && echo x >> docs/basics/01-overview.md'));
blocks(BASH_DOCS, 'a cd to an unset variable, then a heredoc into a plan',
  bashPayload(`cd "$ALPHA_SDLC_UNSET_ROOT" && cat > docs/development/feat/plan-web.md <<'EOF'\n# plan\nEOF`));
blocks(BASH_DOCS, 'a redirect into a doc named through $PWD', bashPayload('echo x > "$PWD/docs/basics/01-overview.md"'));
const greenfield = path.join(os.homedir(), `alpha-sdlc-greenfield-probe-${process.pid}`);
blocks(BASH_DOCS, 'the first profile doc of a repo with no marker yet', bashPayload('echo x > docs/basics/01-overview.md', greenfield));
blocks(BASH_DOCS, 'mkdir then a heredoc into the first profile doc of a new repo',
  bashPayload("mkdir -p docs/basics && cat > docs/basics/01-overview.md <<'EOF'\n# x\nEOF", greenfield));
passes(BASH_DOCS, 'a markdown file outside docs of a repo with no marker yet', bashPayload('echo x > NOTES.md', greenfield));

const workspace = projectFixture('workspace-parent', {
  '.alpha-sdlc/next/feat--web.json': '{}',
  'unrelated-sdk/src/Api.kt': 'class Api\n',
});
sdlcProject(path.join('workspace-parent', 'sdlc-repo'), { 'src/a.ts': 'export const a = 1;\n' });
passes(COMMENTS, 'a workspace parent\'s state directory brings no unrelated sibling repo into scope',
  writePayload(path.join(workspace, 'unrelated-sdk', 'src', 'Api.kt'), '/** Public SDK entry point. */\nclass Api\n'), { cwd: workspace });
blocks(COMMENTS, 'the SDLC repo inside that workspace is still checked',
  writePayload(path.join(workspace, 'sdlc-repo', 'src', 'b.ts'), '// explains b\nexport const b = 1;\n'), { cwd: workspace });

const crlf = sdlcProject('crlf', {
  'docs/development/feat/plan-web.md': '# Plan\r\n\r\n### Stage 1 — [data] `a` — A\r\n\r\n- **Approach:** rung 2 (reuse): X · standard: agrees\r\n' +
    '- **Status:** pending\r\n\r\n### Stage 2 — b\r\n\r\nBuild b.\r\n',
  'docs/development/feat/TRD.md': '# TRD\r\n\r\n## 1. Design\r\n\r\n| A | B |\r\n|---|---|\r\n| 1 | 2 |\r\n',
});
blocks(RUNG, 'a plan edit on CRLF line endings that leaves the Approach a placeholder',
  editPayload(path.join(crlf, 'docs/development/feat/plan-web.md'), '### Stage 2 — b\n\nBuild b.', '### Stage 2 — b\n\n**Approach:** <rung>\n\nBuild b.'),
  { stderrIncludes: ['Ladder rung missing'] });
blocks(TABLES, 'a table edit on CRLF line endings that breaks a row',
  editPayload(path.join(crlf, 'docs/development/feat/TRD.md'), '|---|---|\n| 1 | 2 |', '|---|---|\n| 1 | 2 | 3 |'),
  { stderrIncludes: ['Broken table'] });
blocks(RUNG, 'a section stamp that keeps the <commit> placeholder',
  writePayload(path.join(plans, 'docs/development/stamp/TRD.md'), '# TRD\n\n## 1. Design\n_Approved: 2026-10-09 · <commit>_\n\nText.\n'),
  { stderrIncludes: ['<commit>'] });
blocks(RUNG, 'a hub-alignment stamp that keeps the <commit> placeholder',
  writePayload(path.join(plans, 'docs/development/stamp/TRD-web.md'), '# TRD\n\n| | |\n|---|---|\n| **Hub alignment** | ✅ reviewed 2026-10-09 · hub rev `<commit>` |\n'),
  { stderrIncludes: ['<commit>'] });
passes(RUNG, 'a git command that names <commit> in its own syntax is no placeholder',
  writePayload(path.join(plans, 'docs/development/stamp/plan-web.md'),
    '# Plan\n\n| read one blob | `internal/git/read.go` | `Show` (`cat-file blob <commit>:<path>`) |\n\nThe link keeps the `?ref=<commit>` pin.\n'));
blocks(TABLES, 'the head remedy names the template\'s stamp, approval kept',
  writePayload(inProfiles('docs/basics/02-architecture.md'), POLLUTED_PROFILE_DOC),
  { stderrIncludes: ['`_Generated by `do-project-setup` · commit `<hash>` · approved <YYYY-MM-DD>_`', 'the approval kept', 'prescriptive (pre-code)'] });

for (const testCase of cases) {
  const { cwd, env, stderrIncludes = [] } = testCase.options;
  const { exitCode, stderr } = runHook(testCase.hook, testCase.payload, { cwd, env });
  const missing = stderrIncludes.filter((text) => !stderr.includes(text));
  const verb = testCase.expected === 2 ? 'must block' : 'must pass';
  report(testCase.hook, `${verb}: ${testCase.name}`, exitCode === testCase.expected && !missing.length, [
    `expected exit ${testCase.expected}, got ${exitCode}`,
    missing.length ? `stderr lacks: ${missing.join(' | ')}` : '',
    stderr.trim() ? stderr.trim().split('\n')[0] : '',
  ]);
}

finish();
